# set up database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/code_test
        username: root
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    security:
        user:
            password: test

# set up cloudinary
cloudinary:
    cloud-name: dx97yn40v
    api-key: 885826543631441
    api-secret: nYUc9V4akJUAzK2b7Gf7lcE-ENY

# set up the swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    api-docs:
        path: /v3/api-docs