# set up database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/code_test
        username: root
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    security:
        user:
            password: test