# set up database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/code_test
        username: root
        password: admin
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    security:
        user:
            password: test
        oauth2:
            client:
                registration:
                    google:
                        client-id: 577157149995-o93e8lv3gc7bcurj6p86v73vojmrc9nf.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile

# set up cloudinary
cloudinary:
    cloud-name: dx97yn40v
    api-key: 885826543631441
    api-secret: nYUc9V4akJUAzK2b7Gf7lcE-ENY

# set up the swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    api-docs:
        path: /v3/api-docs
#logging:
#    level:
#      org:
#          springframework:
#                security: TRACE

